### ISSUE TITLE
Is it able to abort the pam authentication during the facial-auth?

### ISSUE THREAD

**Issue by andymatos** [devinaconley/pam-facial-auth#1]
Since face-auth may take some time, is it able to break the facial-auth process and comeback to password authentication?

**Comment by devinaconley** [comment]
@andymatos - yes there is a `timeout` field which can be specified in the generated `config` file. The default is 10 seconds.

https://github.com/devinaconley/pam-facial-auth/blob/1184b9c961959b4bf3b74a0e7f7c22c9541927d7/src/FacialAuth.cpp#L50
